load("//test:rules.bzl", "make_fixture", "make_unit_tests")

MANUAL_TESTS = [
    "keyword_serialization_speed.cpp",
]

SAMPLE_TEST = [
    "coverage.cpp",
    "evaluation.cpp",
]

make_fixture(
    name = "samples",
    hdrs = [
        "fixture/samples.hpp"
    ],
    srcs = [
        "fixture/samples.cpp"
    ],
    deps = [
        "@boost.describe//:boost.describe",
        "@boost.json//:boost.json",
        "//:haikan",
    ],
)


make_unit_tests(
    srcs = SAMPLE_TEST,
    fixtures = [":samples"]
)

make_unit_tests(
    srcs = glob([
        "*.cpp"
    ], exclude = SAMPLE_TEST + MANUAL_TESTS),
)

make_unit_tests(
    srcs = MANUAL_TESTS,
    tags = ["manual"],
)
