load("//test:rules.bzl", "make_fixture", "make_unit_tests")

MANUAL_TESTS = [
    "keyword_serialization_speed.cpp",
]

SAMPLE_TEST = [
    "coverage.cpp",
    "evaluation.cpp",
]

make_fixture(
    name = "samples",
    hdrs = [
        "fixture/samples.hpp"
    ],
    srcs = [
        "fixture/samples.cpp"
    ],
    deps = [
        "@boost.describe//:boost.describe",
        "@boost.json//:boost.json",
        "//:haikan",
    ],
)

make_fixture(
    name = "reflect_types",
    hdrs = [
        "fixture/reflect_types.hpp"
    ],
    deps = [
        "@boost.describe//:boost.describe",
        "@boost.optional//:boost.optional",
        "//:haikan",
    ],
)


make_unit_tests(
    srcs = SAMPLE_TEST,
    fixtures = [":samples"]
)

REFLECT_TESTS = [
    "reflect_basics.cpp",
    "reflect_containers.cpp",
    "reflect_reference.cpp",
]

make_unit_tests(
    srcs = glob([
        "*.cpp"
    ], exclude = SAMPLE_TEST + MANUAL_TESTS + REFLECT_TESTS),
)

make_unit_tests(
    srcs = REFLECT_TESTS,
    fixtures = [":reflect_types"],
)

make_unit_tests(
    srcs = MANUAL_TESTS,
    tags = ["manual"],
)
