@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */


#include "haikan/keywords_lua.hpp"

#if defined(__clang__) || defined(__GNUC__)
#define HAIKAN_KEYWORD_INIT __attribute__((init_priority(101)))
#else
#define HAIKAN_KEYWORD_INIT
#endif

namespace haikan {
namespace lua {

@for keyword in data.ApiKeywords:
impl::Lua@keyword.Class const HAIKAN_KEYWORD_INIT @keyword.Name = {};
@for alias in keyword.Aliases:
impl::Lua@keyword.Class const HAIKAN_KEYWORD_INIT @alias.capitalize() = @keyword.Name;
@end
@end

} // namespace lua
} // namespace haikan
