/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: codegen.expr
 * template: codegen/templates/include/haikan/keywords.hpp
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#pragma once

#include "haikan/impl/signatures.hpp"

namespace haikan {


/// \brief No operation
/// \details
/// Returns true without input validation.
/// Used in place of matchers for uninteresting signals.
extern impl::SignatureConst<::haikan::impl::Keyword::Noop> const Noop;
/// \brief Alias for Noop
extern impl::SignatureConst<::haikan::impl::Keyword::Noop> const _;

/// \brief Null value
extern impl::SignatureConst<::haikan::impl::Keyword::Null> const Null;

/// \brief Logical true
extern impl::SignatureConst<::haikan::impl::Keyword::True> const True;

/// \brief Logical false
extern impl::SignatureConst<::haikan::impl::Keyword::False> const False;

/// \brief Pi constant
extern impl::SignatureConst<::haikan::impl::Keyword::Pi> const Pi;

/// \brief Euler's number
extern impl::SignatureConst<::haikan::impl::Keyword::E> const E;

/// \brief Infinity
extern impl::SignatureConst<::haikan::impl::Keyword::Inf> const Inf;

/// \brief Machine epsilon
extern impl::SignatureConst<::haikan::impl::Keyword::Eps> const Eps;

/// \brief Not a number
extern impl::SignatureConst<::haikan::impl::Keyword::NaN> const NaN;

/// \brief Thread id
/// \details
/// Not really a constant, but useful for
/// branching the test input conditions.
extern impl::SignatureConst<::haikan::impl::Keyword::Thread> const Thread;

/// \brief Sinus function
extern impl::SignatureUnary<::haikan::impl::Keyword::Sin> const Sin;

/// \brief Cosinus function
extern impl::SignatureUnary<::haikan::impl::Keyword::Cos> const Cos;

/// \brief Tangens function
extern impl::SignatureUnary<::haikan::impl::Keyword::Tan> const Tan;

/// \brief Arcsin function
extern impl::SignatureUnary<::haikan::impl::Keyword::Asin> const Asin;

/// \brief Arccos function
extern impl::SignatureUnary<::haikan::impl::Keyword::Acos> const Acos;

/// \brief Arctan function
extern impl::SignatureUnary<::haikan::impl::Keyword::Atan> const Atan;

/// \brief Hyperbolic sin
extern impl::SignatureUnary<::haikan::impl::Keyword::Sinh> const Sinh;

/// \brief Hyperbolic cos
extern impl::SignatureUnary<::haikan::impl::Keyword::Cosh> const Cosh;

/// \brief Hyperbolic tan
extern impl::SignatureUnary<::haikan::impl::Keyword::Tanh> const Tanh;

/// \brief Hyperbolic arcsin
extern impl::SignatureUnary<::haikan::impl::Keyword::Asinh> const Asinh;

/// \brief Hyperbolic arccos
extern impl::SignatureUnary<::haikan::impl::Keyword::Acosh> const Acosh;

/// \brief Hyperbolic arctan
extern impl::SignatureUnary<::haikan::impl::Keyword::Atanh> const Atanh;

/// \brief Exponential (e^x)
extern impl::SignatureUnary<::haikan::impl::Keyword::Exp> const Exp;

/// \brief Error function
extern impl::SignatureUnary<::haikan::impl::Keyword::Erf> const Erf;

/// \brief Error function complement
extern impl::SignatureUnary<::haikan::impl::Keyword::Erfc> const Erfc;

/// \brief Gamma function
extern impl::SignatureUnary<::haikan::impl::Keyword::Gamma> const Gamma;

/// \brief Absolute value
extern impl::SignatureUnary<::haikan::impl::Keyword::Abs> const Abs;

/// \brief Ceil
extern impl::SignatureUnary<::haikan::impl::Keyword::Ceil> const Ceil;

/// \brief Floor
extern impl::SignatureUnary<::haikan::impl::Keyword::Floor> const Floor;

/// \brief Round to nearest integer
/// \details
/// Hint: To round to ndigits precision after the decimal point,
/// use `Mul(ndigits) | Round | Div(ndigits)` combo.
extern impl::SignatureUnary<::haikan::impl::Keyword::Round> const Round;

/// \brief Square root
extern impl::SignatureUnary<::haikan::impl::Keyword::Sqrt> const Sqrt;

/// \brief Sign
extern impl::SignatureUnary<::haikan::impl::Keyword::Sign> const Sign;

/// \brief Negate
extern impl::SignatureUnary<::haikan::impl::Keyword::Neg> const Neg;

/// \brief Addition
extern impl::SignatureBinary<::haikan::impl::Keyword::Add> const Add;

/// \brief Subtraction
extern impl::SignatureBinary<::haikan::impl::Keyword::Sub> const Sub;

/// \brief Multiplication
extern impl::SignatureBinary<::haikan::impl::Keyword::Mul> const Mul;

/// \brief Division
/// \details
/// 1. $[ ] \mapsto [x, y] \mapsto x / y$
/// 2. $[y] \mapsto [x]    \mapsto x / y$
extern impl::SignatureBinary<::haikan::impl::Keyword::Div> const Div;

/// \brief To power
/// \details
/// X to power p
///   1. $[ ] \mapsto [x, p] \mapsto x^p$
///   2. $[p] \mapsto [x]    \mapsto x^p$
extern impl::SignatureBinary<::haikan::impl::Keyword::Pow> const Pow;

/// \brief Logarithm
/// \details
/// Logarithm with base b:
/// 
///   1. $[ ] \mapsto [x, b] \mapsto log_b(x)$
///   2. $[b] \mapsto [x]    \mapsto log_b(x)$
extern impl::SignatureBinary<::haikan::impl::Keyword::Log> const Log;

/// \brief Modulo
/// \details
/// Modulo of x:
/// 
///   1. $[ ] \mapsto [x, m] \mapsto x % m$
///   2. $[m] \mapsto [x]    \mapsto x % m$
extern impl::SignatureBinary<::haikan::impl::Keyword::Mod> const Mod;

/// \brief Quotient
/// \details
/// Quotient of x:
/// 
///   1. $[ ] \mapsto [x, d] \mapsto x // d$
///   2. $[d] \mapsto [x]    \mapsto x // d$
extern impl::SignatureBinary<::haikan::impl::Keyword::Quot> const Quot;

/// \brief Bitwise not
extern impl::SignatureUnary<::haikan::impl::Keyword::BitNot> const BitNot;

/// \brief Bitwise and
extern impl::SignatureBinary<::haikan::impl::Keyword::BitAnd> const BitAnd;

/// \brief Bitwise or
extern impl::SignatureBinary<::haikan::impl::Keyword::BitOr> const BitOr;

/// \brief Bitwise xor
extern impl::SignatureBinary<::haikan::impl::Keyword::BitXor> const BitXor;

/// \brief Bitwise left shift
/// \details
/// 1. $[ ] \mapsto [x, s] \mapsto x \texttt{ << } s$
/// 2. $[s] \mapsto [x]    \mapsto x \texttt{ << } s$
extern impl::SignatureBinary<::haikan::impl::Keyword::Lshift> const Lshift;

/// \brief Bitwise right shift
/// \details
/// 1. $[ ] ↦ [x, s] ↦ x \texttt{ >> } s$
/// 2. $[s] ↦ [x]    ↦ x \texttt{ >> } s$
extern impl::SignatureBinary<::haikan::impl::Keyword::Rshift> const Rshift;

/// \brief Is equal
extern impl::SignatureBinary<::haikan::impl::Keyword::Eq> const Eq;

/// \brief Not equal
extern impl::SignatureBinary<::haikan::impl::Keyword::Ne> const Ne;

/// \brief Lesser than
extern impl::SignatureBinary<::haikan::impl::Keyword::Lt> const Lt;

/// \brief Lesser or equal
extern impl::SignatureBinary<::haikan::impl::Keyword::Le> const Le;

/// \brief Greater than
extern impl::SignatureBinary<::haikan::impl::Keyword::Gt> const Gt;

/// \brief Greater or equal
extern impl::SignatureBinary<::haikan::impl::Keyword::Ge> const Ge;

/// \brief Floating point approximately equal
/// \details
/// Based on numpy.isclose:
/// 
///   abs(x - ref) <= (atol + rtol * abs(ref))
/// 
/// Rhs parameters:
/// 
///   ref: reference value
///   rtol: relative tolerance, default = 1e-05
///   atol: absolute tolerance, default = 1e-08
/// 
/// Rhs dynamic evaluation:
/// 
///   1. ref                -> [ref, default, default]
///   2. [ref]              -> [ref, default, default]
///   3. [ref, rtol]        -> [ref, rtol   , default]
///   4. [ref, rtol, atol]  -> [ref, rtol   , atol   ]
extern impl::SignatureBinary<::haikan::impl::Keyword::Near> const Near;
/// \brief Alias for Near
extern impl::SignatureBinary<::haikan::impl::Keyword::Near> const Approx;

/// \brief Set union
extern impl::SignatureBinary<::haikan::impl::Keyword::Union> const Union;

/// \brief Set intersection
extern impl::SignatureBinary<::haikan::impl::Keyword::Intersect> const Intersect;

/// \brief Set difference
extern impl::SignatureBinary<::haikan::impl::Keyword::Diff> const Diff;

/// \brief Equal as set
extern impl::SignatureBinary<::haikan::impl::Keyword::SetEq> const SetEq;

/// \brief Is subset
extern impl::SignatureBinary<::haikan::impl::Keyword::Subset> const Subset;

/// \brief Is superset
extern impl::SignatureBinary<::haikan::impl::Keyword::Superset> const Superset;

/// \brief Is proper subset
extern impl::SignatureBinary<::haikan::impl::Keyword::PSubset> const PSubset;

/// \brief Is proper superset
extern impl::SignatureBinary<::haikan::impl::Keyword::PSuperset> const PSuperset;

/// \brief Element is in
extern impl::SignatureBinary<::haikan::impl::Keyword::In> const In;

/// \brief Element is not in
extern impl::SignatureBinary<::haikan::impl::Keyword::NotIn> const NotIn;

/// \brief Contains element
extern impl::SignatureBinary<::haikan::impl::Keyword::Ni> const Ni;
/// \brief Alias for Ni
extern impl::SignatureBinary<::haikan::impl::Keyword::Ni> const Contains;

/// \brief Not contains element
extern impl::SignatureBinary<::haikan::impl::Keyword::NotNi> const NotNi;

/// \brief Predicate on boolean transform (aka truthy)
extern impl::SignatureUnary<::haikan::impl::Keyword::Bool> const Bool;
/// \brief Alias for Bool
extern impl::SignatureUnary<::haikan::impl::Keyword::Bool> const Truthy;

/// \brief Logical complement
extern impl::SignatureUnary<::haikan::impl::Keyword::Not> const Not;
/// \brief Alias for Not
extern impl::SignatureUnary<::haikan::impl::Keyword::Not> const Falsy;
/// \brief Alias for Not
extern impl::SignatureUnary<::haikan::impl::Keyword::Not> const Nil;

/// \brief Logical and
/// \details
/// Generic behavior:
///   if first operand is truthy,
///   returns second operand, otherwise first
extern impl::SignatureBinary<::haikan::impl::Keyword::And> const And;

/// \brief Logical or
/// \details
/// Generic behavior:
///   if first operand is truthy,
///   returns first operand, second otherwise
extern impl::SignatureBinary<::haikan::impl::Keyword::Or> const Or;

/// \brief Branching operator
/// \details
/// Branching operator can be used either in
/// Lisp-like mode as `If(predicate, then_expr, else_expr)`,
/// or in pipe mode with Elif or Else operators (see examples).
/// 
/// In pipe mode (without `else_expr` parameter), the chain will produce
/// error if the following order is violated or interrupted:
///  `If [ Elif ]* Else`
/// 
/// In both modes, `then_expr` and `else_expr` are lazy evaluated against
/// run-time argument (which is also true for Elif and Else), making
/// it possible to nest if-else expressions.
extern impl::SignatureVariadic<::haikan::impl::Keyword::If> const If;

/// \brief Else if
/// \details
/// Continuation operator in If-Elif-Else pipe.
/// Will fail if not preceded by If.
/// See If.
extern impl::SignatureVariadic<::haikan::impl::Keyword::Elif> const Elif;

/// \brief Else
/// \details
/// Resolving operator in If-Elif-Else pipe.
/// Will fail if not preceded by If or Elif.
/// See If.
/// 
/// Note: Errors are passed through Else as is,
/// without evaluating the parameter expression.
/// Input errors are handled in preceding If/Elif clauses,
/// while errors produced by If/Elif assumed to be
/// handled  after the Else clause.
extern impl::SignatureBinary<::haikan::impl::Keyword::Else> const Else;

/// \brief Transpose multidimensional list, turning rows into columns
/// \details
/// May be used to zip sequences of equal length.
extern impl::SignatureUnary<::haikan::impl::Keyword::Transp> const Transp;

/// \brief Cartesian product
extern impl::SignatureUnary<::haikan::impl::Keyword::Cartesian> const Cartesian;

/// \brief Reverse sequence
extern impl::SignatureUnary<::haikan::impl::Keyword::Reverse> const Reverse;

/// \brief Filter unique elements
extern impl::SignatureUnary<::haikan::impl::Keyword::Uniques> const Uniques;

/// \brief Extract key-value pairs from object
extern impl::SignatureUnary<::haikan::impl::Keyword::Items> const Items;

/// \brief Extract keys from object
extern impl::SignatureUnary<::haikan::impl::Keyword::Keys> const Keys;

/// \brief Extract values from object
extern impl::SignatureUnary<::haikan::impl::Keyword::Values> const Values;

/// \brief Enumerate sequence
/// \details
/// Enumerate sequence with index.
extern impl::SignatureUnary<::haikan::impl::Keyword::Enumerate> const Enumerate;

/// \brief Flatten nested list
extern impl::SignatureUnary<::haikan::impl::Keyword::Flatten> const Flatten;

/// \brief Put argument into a list
/// \details
/// Equivalent to At([""])
extern impl::SignatureUnary<::haikan::impl::Keyword::ToList> const ToList;

/// \brief First item of sequence
/// \details
/// Equivalent to At(0)
extern impl::SignatureUnary<::haikan::impl::Keyword::First> const First;

/// \brief Last item of sequence
/// \details
/// Equivalent to At(-1)
extern impl::SignatureUnary<::haikan::impl::Keyword::Last> const Last;

/// \brief Uniformly distributed random number in the half-open interval [0.0, 1.0)
extern impl::SignatureUnary<::haikan::impl::Keyword::Rand> const Rand;

/// \brief Uniformly distributed random integer in the given range
/// \details
/// RandInt(x, y) : range is [x, y]
/// RandInt(x)    : range is [0, x] for positive x and [x, 0] for negative
/// RandInt()     : range is [0, RAND_MAX]
extern impl::SignatureVariadic<::haikan::impl::Keyword::RandInt> const RandInt;

/// \brief Produce sequence from parameter using arg as size
/// \details
/// Behavior of `n | Sequence(F)`is similar to n | Flip(Repeat(F)),
/// with the main difference that the parameter is reevaluated for each step,
/// making it possible to utilize side-effects, s.a. with Rand.
extern impl::SignatureBinary<::haikan::impl::Keyword::Sequence> const Sequence;
/// \brief Alias for Sequence
extern impl::SignatureBinary<::haikan::impl::Keyword::Sequence> const Seq;

/// \brief Generate range of numbers
/// \details
/// Return evenly spaced values within a given interval.
/// 
/// Parameters:
/// 
///   1. start: start value
///   2. stop: stop value
///   3. step: step value
/// 
/// Parameters dynamic evaluation:
/// 
///   1. stop: int            -> [0, stop, 1]
///   2. [start, stop]        -> [start, stop, 1]
///   3. [start, stop, step]  -> [start, stop, step]
extern impl::SignatureUnary<::haikan::impl::Keyword::Arange> const Arange;

/// \brief Parse string as json
extern impl::SignatureUnary<::haikan::impl::Keyword::Parse> const Parse;

/// \brief Serialize json as string
extern impl::SignatureUnary<::haikan::impl::Keyword::Str> const Str;
/// \brief Alias for Str
extern impl::SignatureUnary<::haikan::impl::Keyword::Str> const Serialize;

/// \brief Regular expression match
/// \details
/// If input is not a string, match it's serialized form.
extern impl::SignatureBinary<::haikan::impl::Keyword::Re> const Re;
/// \brief Alias for Re
extern impl::SignatureBinary<::haikan::impl::Keyword::Re> const Regex;

/// \brief Format string with the given parameter list.
/// \details
/// Constant expressions are supported for the token list,
/// s.t. `"%s" | Fmt(Pi)`  produces "3.141592653589793E0"
extern impl::SignatureVariadic<::haikan::impl::Keyword::Fmt> const Fmt;
/// \brief Alias for Fmt
extern impl::SignatureVariadic<::haikan::impl::Keyword::Fmt> const Format;

/// \brief Capitalize string
extern impl::SignatureUnary<::haikan::impl::Keyword::Capitalize> const Capitalize;

/// \brief Lower case string
extern impl::SignatureUnary<::haikan::impl::Keyword::LowerCase> const LowerCase;

/// \brief Upper case string
extern impl::SignatureUnary<::haikan::impl::Keyword::UpperCase> const UpperCase;

/// \brief Set cardinality (uniques count)
extern impl::SignatureUnary<::haikan::impl::Keyword::Card> const Card;

/// \brief Sequence size
extern impl::SignatureUnary<::haikan::impl::Keyword::Size> const Size;

/// \brief Summation reduction
/// \details
/// Equivalent to Reduce(Add)
extern impl::SignatureUnary<::haikan::impl::Keyword::Sum> const Sum;

/// \brief Multiplication reduction
/// \details
/// Equivalent to Reduce(Mul)
extern impl::SignatureUnary<::haikan::impl::Keyword::Prod> const Prod;

/// \brief Arythmetic average
extern impl::SignatureUnary<::haikan::impl::Keyword::Avg> const Avg;

/// \brief Sliding-window iteration
/// \details
/// Sliding window iteration by specified window width.
extern impl::SignatureBinary<::haikan::impl::Keyword::Slide> const Slide;

/// \brief Striding iteration
/// \details
/// Striding iteration by specified step width.
/// Reminder subsequence smaller then step width is discarded.
extern impl::SignatureBinary<::haikan::impl::Keyword::Stride> const Stride;

/// \brief Split into chunks of specified max width
/// \details
/// Similar to Stride, but includes the last subsequence
/// smaller then step width.
extern impl::SignatureBinary<::haikan::impl::Keyword::Chunks> const Chunks;

/// \brief Repeat value in list
extern impl::SignatureBinary<::haikan::impl::Keyword::Repeat> const Repeat;

/// \brief Concatenate sequences
extern impl::SignatureBinary<::haikan::impl::Keyword::Cat> const Cat;
/// \brief Alias for Cat
extern impl::SignatureBinary<::haikan::impl::Keyword::Cat> const Concat;

/// \brief Push element into a front of sequence
extern impl::SignatureBinary<::haikan::impl::Keyword::Push> const Push;

/// \brief Transform json value with given query
/// \details
/// Query evaluation rules:
/// 
///   1. Structure index (negative resolves as reverse): $q: int   \mapsto x: list  \mapsto x_q$
///   2. Array slice: $q: slice \mapsto x: list  \mapsto x[start:stop:step]$
///   3. JSON Pointer: $q: str   \mapsto x: any   \mapsto x_q$
///   4. Array pack: $q: list  \mapsto x: any   \mapsto [x_{q_1}, x_{q_2}, ...]$
///   5. Object pack:
///     $\{key: q_1, \$q_2: q_3, ...\} \mapsto x: any \mapsto \{ key: x_{q_1}, q_2: x_{q_3}, ...\}$
/// 
///   Structure index is evaluated as array index or as key-value pair index for objects
///   on order-preserving backends.
/// 
///   Result is null if requested element not found.
extern impl::SignatureBinary<::haikan::impl::Keyword::At> const At;

/// \brief Delete elements from structure by given query
/// \details
/// Possible queries:
///   1. Structure index (negative resolves as reverse)
///   2. JSON Pointer
///   3. List of queries
/// 
/// Structure index is evaluated as array index or as key-value pair index for objects
///   on order-preserving backends.
/// When deleting an object element, resulting items order may change.
extern impl::SignatureBinary<::haikan::impl::Keyword::Del> const Del;
/// \brief Alias for Del
extern impl::SignatureBinary<::haikan::impl::Keyword::Del> const Delete;

/// \brief Update structure at addr with f
/// \details
/// The Upd keyword creates a copy of argument structure
/// with updating the node at given address. The function
/// f is evaluated against node original value or null, if not exist.
/// 
/// JSON Pointers referencing non-existing nodes will create them.
/// Addresses with past-the-end array index are resolved by
/// appending new item.
/// 
/// Possible address queries:
///   1. Structure index (negative resolves as reverse)
///   2. JSON Pointer
///   3. List of queries
extern impl::SignatureVariadic<::haikan::impl::Keyword::Upd> const Upd;
/// \brief Alias for Upd
extern impl::SignatureVariadic<::haikan::impl::Keyword::Upd> const Update;

/// \brief Lookup table function
/// \details
/// Parametrized at design time with fixed array or object,
/// produces the value at corresponding At query given
/// as eval-time argument.
/// Equivalent to ~At(...)
extern impl::SignatureBinary<::haikan::impl::Keyword::Lookup> const Lookup;

/// \brief Cast as given type
/// \details
/// In the current implementation based on JSON,
/// the Cast enables limited transformations on primitive JSON
/// types by reserializing argument as a given type:
/// 
/// ```
/// 0.1 | Cast(type<float>) ↦ 0.1f
/// ~0ULL | Cast(type<std::uint8_t>) ↦ 255
/// int(Foo::Bar) | Cast(type<Foo>) ↦ "Bar"
/// ```
/// 
/// Cast with user-defined types can serve as a decorator filter,
/// potentially handling more complicated logic.
/// For example, expression `Foo::Bar | Cast(type<int>)` yield an error
/// because enum `Foo::Bar` is serialized as string before being passed
/// to cast, and there is no string to int conversion. However,
/// this can be circumvented with a decorator type that has compatible
/// JSON conversion semantics, like haikan::decorators::Underlying<E>:
/// 
/// `Foo::Bar | Cast(Underlying<Foo>)` yields `int(Foo::Bar)` as expected.
extern impl::SignatureCast const Cast;

/// \brief Identity function
extern impl::SignatureUnary<::haikan::impl::Keyword::Id> const Id;

/// \brief Reduce sequence with binary operator
/// \details
/// To set a specific initial value, use composition with Push, e.g.
/// `Push(0) | Fold(Add)`
/// 
/// For reverse operation, see Unfold
extern impl::SignatureBinary<::haikan::impl::Keyword::Fold> const Fold;
/// \brief Alias for Fold
extern impl::SignatureBinary<::haikan::impl::Keyword::Fold> const Reduce;

/// \brief Apply param expr to every element of sequence
extern impl::SignatureBinary<::haikan::impl::Keyword::Map> const Map;

/// \brief Filter sequence by predicate param
extern impl::SignatureBinary<::haikan::impl::Keyword::Filter> const Filter;

/// \brief Count matches by predicate param
extern impl::SignatureBinary<::haikan::impl::Keyword::Count> const Count;

/// \brief Test predicate for each item in a sequence
/// \details
/// Equivalent to `Count(p | Not) | Eq(0)`
extern impl::SignatureBinary<::haikan::impl::Keyword::Each> const Each;

/// \brief Sort list by key function
extern impl::SignatureBinary<::haikan::impl::Keyword::Sort> const Sort;

/// \brief Find the first element that satisfies given predicate
extern impl::SignatureBinary<::haikan::impl::Keyword::Find> const Find;

/// \brief Find json pointer of the first element that satisfies given predicate
extern impl::SignatureBinary<::haikan::impl::Keyword::FindPtr> const FindPtr;

/// \brief Find index of the first element that satisfies given predicate
/// \details
/// Similar to FindPtr, but will integer index or nullptr for non-indexable input.
/// Objects are processed as list of key-value pairs.
extern impl::SignatureBinary<::haikan::impl::Keyword::FindIdx> const FindIdx;

/// \brief Min value by key function
extern impl::SignatureBinary<::haikan::impl::Keyword::Min> const Min;

/// \brief Max value by key function
extern impl::SignatureBinary<::haikan::impl::Keyword::Max> const Max;

/// \brief Min value index by key function
extern impl::SignatureBinary<::haikan::impl::Keyword::Argmin> const Argmin;

/// \brief Max value index by key function
extern impl::SignatureBinary<::haikan::impl::Keyword::Argmax> const Argmax;

/// \brief Apply recursion to parameter expr and initial value
/// \details
/// Inference rules:
/// 
///   - `n | Recur(x, f)` $\mapsto ◯ⁿ f(x)$, or
///   - `Q(p) | Recur(x₀, f)` $\mapsto x_k$, where
/// 
///     - $x_{i+1} = f(x_i)$
///     - $p(x_{i}) = \top \quad \forall i \le k$
///     - $p(x_{i+1}) = \bot$ (exit condition)
extern impl::SignatureVariadic<::haikan::impl::Keyword::Recur> const Recur;

/// \brief Put results of recursive fn call on initial value into an array
/// \details
/// 
/// Inference rules:
/// 
///   - `n | Unfold(x, f)`$\mapsto [x_0, x_1, ...,  x_n]$, or
///   - `Q(p) | Unfold(x₀, f)` $\mapsto [x_0, x_1, ...,  x_k]$, where
/// 
///     - $x_{i+1} = f(x_i)$
///     - $p(x_{i}) = \top \quad \forall i \le k$
///     - $p(x_{i+1}) = \bot$ (exit condition)
extern impl::SignatureVariadic<::haikan::impl::Keyword::Unfold> const Unfold;

/// \brief Bind type-specific operator handler to function
/// \details
/// Expression Op(op, f) instructs f to use op operator on
/// invocation instead of the default generic.
/// 
/// Operator parameter singleton can be referenced with a
/// string key or constructed in place using type<T> tag.
/// 
/// This operator handler is propagated downstream to all terminal
/// subexpression in `f`.
/// The result of `f(x)` is not decorated as type<T>.
extern impl::SignatureOp const Op;
/// \brief Alias for Op
extern impl::SignatureOp const Overload;

/// \brief Bind design-time parameters to function.
extern impl::SignatureBinary<::haikan::impl::Keyword::Bind> const Bind;

/// \brief Symbolic binding of the inline function
/// \details
/// Expression `Fn(reference, expr)` creates a symbolic binding between the given
/// reference and an expression, making the expression callable by name within
/// the evaluation context.
/// 
/// The referenced expression is inlined at the call site and evaluated with
/// the current input. The reference is available to the bound expression itself
/// and to all its subexpressions, enabling arbitrary recursion.
/// 
/// Each invocation of a function bound with `Fn` establishes a local scope for
/// argument bindings created via `Link`, forming a lexical closure over the
/// surrounding bindings. Argument links from outer scopes are captured by the
/// function and remain accessible unless shadowed by a local binding.
/// Such captured values can be explicitly read using the `Get` expression
/// 
/// Function bindings are shared across the whole expression and are immutable:
/// once a reference is bound with `Fn`, it cannot be redefined or reset.
/// 
/// **Infix operator form (left shift)**:
/// 
/// `"$f" << E` ≡ `Fn("$f", E)`
extern impl::SignatureVariadic<::haikan::impl::Keyword::Fn> const Fn;

/// \brief Symbolic binding of the input value
/// \details
/// Capture the current input value and associate it with a symbolic
/// reference represented by a dollar-prefixed string, e.g. `"$x"`.
/// 
/// On its first evaluation, the reference stores the input value (similar to
/// variable initialization) and passes the value further through the pipeline.
/// On subsequent evaluations within the same scope, the stored value is returned,
/// acting as an immutable constant.
/// 
/// A `Link` instance cannot be reset after its first access. However, it may be
/// shadowed by another binding with the same reference name in a nested scope,
/// such as a recursive call created with `Fn`.
/// 
/// The reference name following the `$` sign must not be enclosed in `[]`, `{}`,
/// or `()`, as those formats are reserved for internal use.
extern impl::SignatureBinary<::haikan::impl::Keyword::Link> const Link;

/// \brief Load linked value (maybe a closure) or return null
/// \details
/// Explicitly load the value bound to a symbolic reference without
/// triggering capture semantics.
/// 
/// In contexts where a `$`-prefixed reference would otherwise attempt to
/// initialize a new binding, `Get` forces a read of an existing binding from
/// the nearest enclosing scope. If no such binding exists, `null` is returned.
/// 
/// This is particularly useful when working with immutable closures and
/// recursive expressions, where it is necessary to distinguish between
/// reading an upvalue and introducing a new local binding.
extern impl::SignatureBinary<::haikan::impl::Keyword::Get> const Get;

/// \brief Load value from the test environment using json pointer
/// \details
/// Load the the value from a global environment table with a given JSON Pointer.
extern impl::SignatureBinary<::haikan::impl::Keyword::EnvLoad> const EnvLoad;

/// \brief Store value in the test environment using json pointer
/// \details
/// Capture the argument value and store it in a global environment table with a given JSON Pointer, passing the value further similarly to Link.
extern impl::SignatureBinary<::haikan::impl::Keyword::EnvStore> const EnvStore;

/// \brief Match any predicate
extern impl::SignatureVariadic<::haikan::impl::Keyword::Any> const Any;

/// \brief Match all predicates
extern impl::SignatureVariadic<::haikan::impl::Keyword::All> const All;

/// \brief Saturate matches in order
extern impl::SignatureVariadic<::haikan::impl::Keyword::Saturate> const Saturate;

/// \brief Pipe functions in left-to-right composition
extern impl::SignatureVariadic<::haikan::impl::Keyword::Pipe> const Pipe;

/// \brief Pack expressions into an tuple without evaluation
extern impl::SignatureVariadic<::haikan::impl::Keyword::Tuple> const Tuple;

/// \brief Pack results from enveloped functions into an array
/// \details
/// Parallel composition operator:
/// 
/// ```
/// x | Fork(f1, f2, ..., fn) ↦ [f1(x0), f2(x), ..., fn(x)]
/// ```
extern impl::SignatureVariadic<::haikan::impl::Keyword::Fork> const Fork;

/// \brief Flip design-time and eval-time parameters.
/// \details
/// Useful for binding lhs operands to non-commutative
/// operators. Unlike Haskell's flip, won't change the
/// order or eval-time parameters - for that case use
/// the Reverse keyword instead.
/// 
/// **Prefix operator form (tilde)**:
/// 
/// Flip(Div(1)) ≡ ~Div(1)
extern impl::SignatureBinary<::haikan::impl::Keyword::Flip> const Flip;

/// \brief Evaluate function and print evaluation log to stderr
extern impl::SignatureBinary<::haikan::impl::Keyword::Dbg> const Dbg;
/// \brief Alias for Dbg
extern impl::SignatureBinary<::haikan::impl::Keyword::Dbg> const Debug;

/// \brief Flip designtime and run-time parameters, evaluating input as expression
extern impl::SignatureBinary<::haikan::impl::Keyword::Eval> const Eval;

/// \brief Evaluate function and return result or null if it returns error
extern impl::SignatureBinary<::haikan::impl::Keyword::Try> const Try;

/// \brief Introspect expression keyword.
extern impl::SignatureUnary<::haikan::impl::Keyword::Kwrd> const Kwrd;

/// \brief Introspect expression parameters.
extern impl::SignatureUnary<::haikan::impl::Keyword::Prms> const Prms;
/// \brief Alias for Prms
extern impl::SignatureUnary<::haikan::impl::Keyword::Prms> const Parameters;

/// \brief Quote parameter, similar to lisp quotation.
/// \details
/// Quotation lifts any parameter to constant, s.t.
/// produced expression will return the design-time parameter
/// on evaluation, ignoring input. If evaluable expression
/// is passed, it is returned unevaluated.
/// Unlike plain literals which can be treated
/// as predicate matchers in certain context, Q(x) is always
/// a constant expression discarding input.
/// ~Q (Flip(Q)) is equivalent to Id.
extern impl::SignatureBinary<::haikan::impl::Keyword::Q> const Q;
/// \brief Alias for Q
extern impl::SignatureBinary<::haikan::impl::Keyword::Q> const C;
/// \brief Alias for Q
extern impl::SignatureBinary<::haikan::impl::Keyword::Q> const Const;

/// \brief Return x if not null, else return default value
extern impl::SignatureBinary<::haikan::impl::Keyword::D> const D;
/// \brief Alias for D
extern impl::SignatureBinary<::haikan::impl::Keyword::D> const Default;

/// \brief Error object
/// \details
/// Error object handling the message and context info
extern impl::SignatureErr const Err;
/// \brief Alias for Err
extern impl::SignatureErr const Error;

/// \brief Test the argument is err expression
extern impl::SignatureUnary<::haikan::impl::Keyword::IsErr> const IsErr;
/// \brief Alias for IsErr
extern impl::SignatureUnary<::haikan::impl::Keyword::IsErr> const Iserror;

/// \brief Return argument if it holds assertion or error otherwise.
extern impl::SignatureBinary<::haikan::impl::Keyword::Assert> const Assert;

/// \brief Same as id, but also prints identifier parameter to debug log.
extern impl::SignatureBinary<::haikan::impl::Keyword::Trace> const Trace;

/// \brief Preprocessing token
/// \details
/// String token that can be substituted with arbitrary expression
/// on expression preprocessing.
extern impl::SignatureBinary<::haikan::impl::Keyword::PreProc> const PreProc;

} // namespace haikan
