@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#pragma once

#include "haikan/impl/signatures_lua.hpp"

namespace haikan {
namespace lua {

@for keyword in data.ApiKeywords:

/// \brief @keyword.DocBrief
    @if details := keyword.DocDetails:
/// \details
        @for line in details.split('\n'):
/// @line
        @end
    @end
extern impl::Lua@keyword.Class const @keyword.Name;
@for alias in keyword.Aliases:
/// \brief Alias for @keyword.Name
extern impl::Lua@keyword.Class const @alias.capitalize();
@end
@end

} // namespace lua
} // namespace haikan
