@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#include <boost/spirit/include/qi.hpp>

#include "haikan/impl/keyword.hpp"
#include "haikan/impl/keyword_grammar.hpp"


namespace qi = boost::spirit::qi;

namespace haikan {
namespace impl {


KeywordSymbol::KeywordSymbol()
{
    add
@for keyword in data.Keywords:
    ("@keyword.Name", Keyword::@keyword.Name)
    @if symbol := keyword.Symbol:
    ("@symbol", Keyword::@keyword.Name)
    @end
    @for alias in keyword.Aliases:
    ("@alias", Keyword::@keyword.Name)
    @end
@end
    ;
}


KeywordGrammar::KeywordGrammar()
    : KeywordGrammar::base_type(start)
{
    using boost::spirit::qi::eps;
    using boost::spirit::qi::_val;
    using boost::spirit::qi::_1;

    start = eps [_val = Keyword::Undefined] >>
        (
            +keyword_symbol [_val = _1]
        )
    ;
}

} // namespace impl
} // namespace haikan
