@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */


#include "haikan/impl/keyword_to_str.hpp"


namespace haikan {
namespace impl {


boost::json::string_view keyword_to_str(Keyword const& kw)
{
    switch(kw)
    {

@for keyword in data.Keywords:
    case Keyword::@keyword.Name: { return "@keyword.Name"; break; }
@end
    default:
        return "Undefined";
    }
}

} // namespace impl
} // namespace haikan
