/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: codegen.expr
 * template: codegen/templates/src/keywords_lua.cpp
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */


#include "haikan/keywords_lua.hpp"

#if defined(__clang__) || defined(__GNUC__)
#define HAIKAN_KEYWORD_INIT __attribute__((init_priority(101)))
#else
#define HAIKAN_KEYWORD_INIT
#endif

namespace haikan {
namespace lua {

impl::LuaSignatureConst<::haikan::impl::Keyword::Noop> const HAIKAN_KEYWORD_INIT Noop = {};
impl::LuaSignatureConst<::haikan::impl::Keyword::Noop> const HAIKAN_KEYWORD_INIT _ = Noop;
impl::LuaSignatureConst<::haikan::impl::Keyword::Null> const HAIKAN_KEYWORD_INIT Null = {};
impl::LuaSignatureConst<::haikan::impl::Keyword::True> const HAIKAN_KEYWORD_INIT True = {};
impl::LuaSignatureConst<::haikan::impl::Keyword::False> const HAIKAN_KEYWORD_INIT False = {};
impl::LuaSignatureConst<::haikan::impl::Keyword::Pi> const HAIKAN_KEYWORD_INIT Pi = {};
impl::LuaSignatureConst<::haikan::impl::Keyword::E> const HAIKAN_KEYWORD_INIT E = {};
impl::LuaSignatureConst<::haikan::impl::Keyword::Inf> const HAIKAN_KEYWORD_INIT Inf = {};
impl::LuaSignatureConst<::haikan::impl::Keyword::Eps> const HAIKAN_KEYWORD_INIT Eps = {};
impl::LuaSignatureConst<::haikan::impl::Keyword::NaN> const HAIKAN_KEYWORD_INIT NaN = {};
impl::LuaSignatureConst<::haikan::impl::Keyword::Thread> const HAIKAN_KEYWORD_INIT Thread = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Sin> const HAIKAN_KEYWORD_INIT Sin = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Cos> const HAIKAN_KEYWORD_INIT Cos = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Tan> const HAIKAN_KEYWORD_INIT Tan = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Asin> const HAIKAN_KEYWORD_INIT Asin = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Acos> const HAIKAN_KEYWORD_INIT Acos = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Atan> const HAIKAN_KEYWORD_INIT Atan = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Sinh> const HAIKAN_KEYWORD_INIT Sinh = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Cosh> const HAIKAN_KEYWORD_INIT Cosh = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Tanh> const HAIKAN_KEYWORD_INIT Tanh = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Asinh> const HAIKAN_KEYWORD_INIT Asinh = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Acosh> const HAIKAN_KEYWORD_INIT Acosh = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Atanh> const HAIKAN_KEYWORD_INIT Atanh = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Exp> const HAIKAN_KEYWORD_INIT Exp = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Erf> const HAIKAN_KEYWORD_INIT Erf = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Erfc> const HAIKAN_KEYWORD_INIT Erfc = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Gamma> const HAIKAN_KEYWORD_INIT Gamma = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Abs> const HAIKAN_KEYWORD_INIT Abs = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Ceil> const HAIKAN_KEYWORD_INIT Ceil = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Floor> const HAIKAN_KEYWORD_INIT Floor = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Round> const HAIKAN_KEYWORD_INIT Round = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Sqrt> const HAIKAN_KEYWORD_INIT Sqrt = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Sign> const HAIKAN_KEYWORD_INIT Sign = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Neg> const HAIKAN_KEYWORD_INIT Neg = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Add> const HAIKAN_KEYWORD_INIT Add = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Sub> const HAIKAN_KEYWORD_INIT Sub = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Mul> const HAIKAN_KEYWORD_INIT Mul = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Div> const HAIKAN_KEYWORD_INIT Div = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Pow> const HAIKAN_KEYWORD_INIT Pow = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Log> const HAIKAN_KEYWORD_INIT Log = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Mod> const HAIKAN_KEYWORD_INIT Mod = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Quot> const HAIKAN_KEYWORD_INIT Quot = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::BitNot> const HAIKAN_KEYWORD_INIT BitNot = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::BitAnd> const HAIKAN_KEYWORD_INIT BitAnd = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::BitOr> const HAIKAN_KEYWORD_INIT BitOr = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::BitXor> const HAIKAN_KEYWORD_INIT BitXor = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Lshift> const HAIKAN_KEYWORD_INIT Lshift = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Rshift> const HAIKAN_KEYWORD_INIT Rshift = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Eq> const HAIKAN_KEYWORD_INIT Eq = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Ne> const HAIKAN_KEYWORD_INIT Ne = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Lt> const HAIKAN_KEYWORD_INIT Lt = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Le> const HAIKAN_KEYWORD_INIT Le = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Gt> const HAIKAN_KEYWORD_INIT Gt = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Ge> const HAIKAN_KEYWORD_INIT Ge = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Near> const HAIKAN_KEYWORD_INIT Near = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Near> const HAIKAN_KEYWORD_INIT Approx = Near;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Union> const HAIKAN_KEYWORD_INIT Union = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Intersect> const HAIKAN_KEYWORD_INIT Intersect = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Diff> const HAIKAN_KEYWORD_INIT Diff = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::SetEq> const HAIKAN_KEYWORD_INIT SetEq = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Subset> const HAIKAN_KEYWORD_INIT Subset = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Superset> const HAIKAN_KEYWORD_INIT Superset = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::PSubset> const HAIKAN_KEYWORD_INIT PSubset = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::PSuperset> const HAIKAN_KEYWORD_INIT PSuperset = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::In> const HAIKAN_KEYWORD_INIT In = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::NotIn> const HAIKAN_KEYWORD_INIT NotIn = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Ni> const HAIKAN_KEYWORD_INIT Ni = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Ni> const HAIKAN_KEYWORD_INIT Contains = Ni;
impl::LuaSignatureBinary<::haikan::impl::Keyword::NotNi> const HAIKAN_KEYWORD_INIT NotNi = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Bool> const HAIKAN_KEYWORD_INIT Bool = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Bool> const HAIKAN_KEYWORD_INIT Truthy = Bool;
impl::LuaSignatureUnary<::haikan::impl::Keyword::Not> const HAIKAN_KEYWORD_INIT Not = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Not> const HAIKAN_KEYWORD_INIT Falsy = Not;
impl::LuaSignatureUnary<::haikan::impl::Keyword::Not> const HAIKAN_KEYWORD_INIT Nil = Not;
impl::LuaSignatureBinary<::haikan::impl::Keyword::And> const HAIKAN_KEYWORD_INIT And = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Or> const HAIKAN_KEYWORD_INIT Or = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::If> const HAIKAN_KEYWORD_INIT If = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Elif> const HAIKAN_KEYWORD_INIT Elif = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Else> const HAIKAN_KEYWORD_INIT Else = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Transp> const HAIKAN_KEYWORD_INIT Transp = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Cartesian> const HAIKAN_KEYWORD_INIT Cartesian = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Reverse> const HAIKAN_KEYWORD_INIT Reverse = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Uniques> const HAIKAN_KEYWORD_INIT Uniques = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Items> const HAIKAN_KEYWORD_INIT Items = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Keys> const HAIKAN_KEYWORD_INIT Keys = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Values> const HAIKAN_KEYWORD_INIT Values = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Enumerate> const HAIKAN_KEYWORD_INIT Enumerate = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Flatten> const HAIKAN_KEYWORD_INIT Flatten = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::ToList> const HAIKAN_KEYWORD_INIT ToList = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::First> const HAIKAN_KEYWORD_INIT First = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Last> const HAIKAN_KEYWORD_INIT Last = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Rand> const HAIKAN_KEYWORD_INIT Rand = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::RandInt> const HAIKAN_KEYWORD_INIT RandInt = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Sequence> const HAIKAN_KEYWORD_INIT Sequence = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Sequence> const HAIKAN_KEYWORD_INIT Seq = Sequence;
impl::LuaSignatureUnary<::haikan::impl::Keyword::Arange> const HAIKAN_KEYWORD_INIT Arange = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Parse> const HAIKAN_KEYWORD_INIT Parse = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Str> const HAIKAN_KEYWORD_INIT Str = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Str> const HAIKAN_KEYWORD_INIT Serialize = Str;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Re> const HAIKAN_KEYWORD_INIT Re = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Re> const HAIKAN_KEYWORD_INIT Regex = Re;
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Fmt> const HAIKAN_KEYWORD_INIT Fmt = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Fmt> const HAIKAN_KEYWORD_INIT Format = Fmt;
impl::LuaSignatureUnary<::haikan::impl::Keyword::Capitalize> const HAIKAN_KEYWORD_INIT Capitalize = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::LowerCase> const HAIKAN_KEYWORD_INIT LowerCase = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::UpperCase> const HAIKAN_KEYWORD_INIT UpperCase = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Card> const HAIKAN_KEYWORD_INIT Card = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Size> const HAIKAN_KEYWORD_INIT Size = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Sum> const HAIKAN_KEYWORD_INIT Sum = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Prod> const HAIKAN_KEYWORD_INIT Prod = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Avg> const HAIKAN_KEYWORD_INIT Avg = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Slide> const HAIKAN_KEYWORD_INIT Slide = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Stride> const HAIKAN_KEYWORD_INIT Stride = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Chunks> const HAIKAN_KEYWORD_INIT Chunks = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Repeat> const HAIKAN_KEYWORD_INIT Repeat = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Cat> const HAIKAN_KEYWORD_INIT Cat = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Cat> const HAIKAN_KEYWORD_INIT Concat = Cat;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Push> const HAIKAN_KEYWORD_INIT Push = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::At> const HAIKAN_KEYWORD_INIT At = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Del> const HAIKAN_KEYWORD_INIT Del = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Del> const HAIKAN_KEYWORD_INIT Delete = Del;
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Upd> const HAIKAN_KEYWORD_INIT Upd = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Upd> const HAIKAN_KEYWORD_INIT Update = Upd;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Lookup> const HAIKAN_KEYWORD_INIT Lookup = {};
impl::LuaSignatureCast const HAIKAN_KEYWORD_INIT Cast = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Id> const HAIKAN_KEYWORD_INIT Id = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Fold> const HAIKAN_KEYWORD_INIT Fold = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Fold> const HAIKAN_KEYWORD_INIT Reduce = Fold;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Map> const HAIKAN_KEYWORD_INIT Map = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Filter> const HAIKAN_KEYWORD_INIT Filter = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Count> const HAIKAN_KEYWORD_INIT Count = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Each> const HAIKAN_KEYWORD_INIT Each = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Sort> const HAIKAN_KEYWORD_INIT Sort = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Find> const HAIKAN_KEYWORD_INIT Find = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::FindPtr> const HAIKAN_KEYWORD_INIT FindPtr = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::FindIdx> const HAIKAN_KEYWORD_INIT FindIdx = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Min> const HAIKAN_KEYWORD_INIT Min = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Max> const HAIKAN_KEYWORD_INIT Max = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Argmin> const HAIKAN_KEYWORD_INIT Argmin = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Argmax> const HAIKAN_KEYWORD_INIT Argmax = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Recur> const HAIKAN_KEYWORD_INIT Recur = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Unfold> const HAIKAN_KEYWORD_INIT Unfold = {};
impl::LuaSignatureOp const HAIKAN_KEYWORD_INIT Op = {};
impl::LuaSignatureOp const HAIKAN_KEYWORD_INIT Overload = Op;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Bind> const HAIKAN_KEYWORD_INIT Bind = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Fn> const HAIKAN_KEYWORD_INIT Fn = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Link> const HAIKAN_KEYWORD_INIT Link = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Get> const HAIKAN_KEYWORD_INIT Get = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::EnvLoad> const HAIKAN_KEYWORD_INIT EnvLoad = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::EnvStore> const HAIKAN_KEYWORD_INIT EnvStore = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Any> const HAIKAN_KEYWORD_INIT Any = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::All> const HAIKAN_KEYWORD_INIT All = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Saturate> const HAIKAN_KEYWORD_INIT Saturate = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Pipe> const HAIKAN_KEYWORD_INIT Pipe = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Tuple> const HAIKAN_KEYWORD_INIT Tuple = {};
impl::LuaSignatureVariadic<::haikan::impl::Keyword::Fork> const HAIKAN_KEYWORD_INIT Fork = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Flip> const HAIKAN_KEYWORD_INIT Flip = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Dbg> const HAIKAN_KEYWORD_INIT Dbg = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Dbg> const HAIKAN_KEYWORD_INIT Debug = Dbg;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Eval> const HAIKAN_KEYWORD_INIT Eval = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Try> const HAIKAN_KEYWORD_INIT Try = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Kwrd> const HAIKAN_KEYWORD_INIT Kwrd = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Prms> const HAIKAN_KEYWORD_INIT Prms = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::Prms> const HAIKAN_KEYWORD_INIT Parameters = Prms;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Q> const HAIKAN_KEYWORD_INIT Q = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Q> const HAIKAN_KEYWORD_INIT C = Q;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Q> const HAIKAN_KEYWORD_INIT Const = Q;
impl::LuaSignatureBinary<::haikan::impl::Keyword::D> const HAIKAN_KEYWORD_INIT D = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::D> const HAIKAN_KEYWORD_INIT Default = D;
impl::LuaSignatureErr const HAIKAN_KEYWORD_INIT Err = {};
impl::LuaSignatureErr const HAIKAN_KEYWORD_INIT Error = Err;
impl::LuaSignatureUnary<::haikan::impl::Keyword::IsErr> const HAIKAN_KEYWORD_INIT IsErr = {};
impl::LuaSignatureUnary<::haikan::impl::Keyword::IsErr> const HAIKAN_KEYWORD_INIT Iserror = IsErr;
impl::LuaSignatureBinary<::haikan::impl::Keyword::Assert> const HAIKAN_KEYWORD_INIT Assert = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::Trace> const HAIKAN_KEYWORD_INIT Trace = {};
impl::LuaSignatureBinary<::haikan::impl::Keyword::PreProc> const HAIKAN_KEYWORD_INIT PreProc = {};

} // namespace lua
} // namespace haikan
