@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: codegen.expr
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#pragma once

#include <cstdint>
#include "haikan/impl/keyword.hpp"

namespace haikan {
namespace impl {


namespace attr
{
constexpr std::uint32_t is_const       = 1 <<  1;
constexpr std::uint32_t is_unary       = 1 <<  2;
constexpr std::uint32_t is_binary      = 1 <<  3;
constexpr std::uint32_t is_variadic    = 1 <<  4;
constexpr std::uint32_t is_predicate   = 1 <<  5;
constexpr std::uint32_t is_operator    = 1 <<  6;
constexpr std::uint32_t is_hiord       = 1 <<  7;
constexpr std::uint32_t is_noop        = 1 <<  8;
constexpr std::uint32_t is_literal     = 1 <<  9;
constexpr std::uint32_t is_quote       = 1 << 10;
constexpr std::uint32_t is_preproc     = 1 << 11;
constexpr std::uint32_t is_error       = 1 << 12;
constexpr std::uint32_t is_pipe        = 1 << 13;
constexpr std::uint32_t is_fork        = 1 << 14;
constexpr std::uint32_t is_overload    = 1 << 15;
constexpr std::uint32_t is_infix_chain = 1 << 16;
constexpr std::uint32_t is_autogen     = 1 << 17;
constexpr std::uint32_t is_sideeffect  = 1 << 18;
constexpr std::uint32_t is_single_form = 1 << 19;
}


constexpr std::uint32_t keyword_attributes(Keyword const& oc)
{
    using namespace attr;
    switch (oc)
    {
@for keyword in data.Keywords:
    case Keyword::@keyword.Name: return @keyword.Attributes;
@end
    default:
        return 0U;
    }
}

} // namespace impl
} // namespace haikan
