@require(data)
/**
 * \file
 * \copyright (c) Copyright 2024-2025 Zenseact AB
 * \license SPDX-License-Identifier: Apache-2.0
 *
 * \details Autogenerated file - do not change!
 *
 * app: @appname
 * template: @template
 *
 * How to update:
 * 1. Update the template
 * 2. Run `python -m codegen` in the project root
 * 3. Commit changes
 */

#pragma once

#include <cstdint>

namespace haikan {
namespace impl {


/// Chan keyword opcode
enum class Keyword : std::uint64_t
{
    Undefined,
@for keyword in data.Keywords:

    /// @keyword.Name
    @keyword.Name,
@end

    _count
};


} // namespace impl
} // namespace haikan
